### ISSUE TITLE
camskyrad Movie Not in Registry

### ISSUE THREAD

**Issue by AdamTheisen** [ARM-DOE/arm-test-data#17]
Hello,

I tried to import the following and it gave me the below error but I do see the file in the registry (nsacamskyradmovieC1.a1.20240401.100300.mpg)

`import act.tests.sample_files`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/atheisen/Code/ACT/act/tests/sample_files.py", line 11, in <module>
    EXAMPLE_MPEG = DATASETS.fetch('nsacamskyradmovieC1.a1.20240401.100300.mpg')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/pooch/core.py", line 561, in fetch
    self._assert_file_in_registry(fname)
  File "/opt/anaconda3/lib/python3.11/site-packages/pooch/core.py", line 609, in _assert_file_in_registry
    raise ValueError(f"File '{fname}' is not in the registry.")
ValueError: File 'nsacamskyradmovieC1.a1.20240401.100300.mpg' is not in the registry.
```

**Comment by zssherman** [comment]
@AdamTheisen What version do you have of arm_test_data? I did a release a week or so ago that should have fixed the issue?
